/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#135137",
        "on-primary-container": "#005b6b",
        "tertiary-fixed": "#ffe17c",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#231b00",
        "secondary-fixed-dim": "#97d4b2",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#004e5c",
        "primary-fixed": "#acedff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#645100",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "tertiary-container": "#e6c44c",
        "on-error": "#ffffff",
        "secondary-container": "#b0edcb",
        "on-secondary-fixed": "#002113",
        "on-surface": "#191c1e",
        "on-surface-variant": "#3e484c",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#7bd3ea",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "outline": "#6e797c",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "secondary": "#2f694e",
        "tertiary": "#715c00",
        "inverse-primary": "#7bd3ea",
        "primary": "#00687a",
        "accent": "#2f694e",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#001f26",
        "surface-tint": "#00687a",
        "primary-container": "#7bd3ea",
        "on-secondary-container": "#336d52",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "outline-variant": "#bec8cc",
        "on-tertiary-fixed-variant": "#564500",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#b3f0cd",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#e6c44c",
        
        // Shadcn UI required defaults mapping
        border: "#bec8cc",
        input: "#bec8cc",
        ring: "#00687a",
        foreground: "#191c1e",
        muted: {
          DEFAULT: "#e0e3e5",
          foreground: "#3e484c",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#191c1e",
        },
        card: {
          DEFAULT: "rgba(255, 255, 255, 0.7)",
          foreground: "#191c1e",
        },
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "container-max": "1200px"
      },
      fontFamily: {
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
